### ISSUE TITLE
How to configure the device without an app

### ISSUE THREAD

**Issue by brunofvalli** [excaliburpartners/EnergySmartBridge#4]
I know this is not about this code.

This seems to be a community about this device.

How do I add the device to my network without the app? Since it seems the app has been removed from the store.

**Comment by rwagoner** [comment]
The manual is available below. You should be able to connect to the device over wifi.

https://www.lowes.com/pdf/Energy_Smart_Electric_Water_Heater_Controller.pdf

**Comment by brunofvalli** [comment]
Thank you for the quick answer
